<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/09/22 14:01:15
sfConfig::add(array(
  'app_sf_guard_plugin_routes_register' => true,
  'app_sf_guard_plugin_success_signout_url' => 'home/index',
  'app_sf_guard_plugin_success_signin_url' => 'home/dashboard',
  'app_core_version' => '1.0.0',
  'app_core_stability' => 'stable',
));
