<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/09/22 22:01:25
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'changelanguage' => 
  array (
    'is_secure' => false,
  ),
  'index' => 
  array (
    'is_secure' => false,
  ),
  'about' => 
  array (
    'is_secure' => false,
  ),
  'faq' => 
  array (
    'is_secure' => false,
  ),
  'join' => 
  array (
    'is_secure' => false,
  ),
  'change-language' => 
  array (
    'is_secure' => false,
  ),
);
