<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/09/22 22:01:17
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'changelanguage' => 
  array (
    'is_secure' => false,
  ),
);
