<?php

/**
 * Company
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    devpuppy
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Company extends BaseCompany
{
	public function save(Doctrine_Connection $conn = null)
	{
		if ($this->isNew() )
		{
			$now = $this->getCreatedAt() ? $this->getDateTimeObject('created_at')->format('U') : time();
			$this->setCreatedAt(date('Y-m-d H:i:s', $now));
		}
		$now = time();
		$this->setUpdatedAt(date('Y-m-d H:i:s', $now));
	
		return parent::save($conn);
	}
}