<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addappluginconfig extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ap_plugin_config', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'pluginname' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 50,
             ),
             'config_option' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 250,
             ),
             'config_value' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ap_plugin_config');
    }
}