<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/09/21 21:25:11

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=authpuppy',
  'username' => 'root',
  'password' => 123456,
  'name' => 'doctrine',
)),);
