<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/09/21 22:15:53
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'admin',
  ),
  'changelanguage' => 
  array (
    'is_secure' => false,
  ),
);
