<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/09/21 22:14:56
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'changelanguage' => 
  array (
    'is_secure' => false,
  ),
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
);
