<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/09/21 22:15:40
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'support',
  ),
  'changelanguage' => 
  array (
    'is_secure' => false,
  ),
  'login' => 
  array (
    'is_secure' => false,
  ),
  'portal' => 
  array (
    'is_secure' => false,
  ),
  'auth' => 
  array (
    'is_secure' => false,
  ),
  'ping' => 
  array (
    'is_secure' => false,
  ),
  'gwmessage' => 
  array (
    'is_secure' => false,
  ),
  'logout' => 
  array (
    'is_secure' => false,
  ),
);
